sudo: required

language: java

services:
- docker

after_success:
- docker network create --driver bridge group5
- docker pull mongo
- docker run -d --name mongo-dbserver --network group5 mongo
- docker build -t group5 .
- docker run --network group5 group5